Repository NOAA-EMC/UPP, pull requests merged in 2021-09, with the labels that each got.

#381 Enable MPMD srun calls for Jet
  ush/fv3gfs_downstream_nems.sh
Labels: enhancement, Ready for Review, No Baseline Change

#378 adding extra surface fields to the model output
  parm/params_grib2_tbl_new
  parm/params_grib2_tbl_new.text
  parm/post_avblflds.xml
  parm/postcntrl_gfs.xml
  parm/postcntrl_gfs_anl.xml
  parm/postcntrl_gfs_f00.xml
  parm/postcntrl_gfs_f00_two.xml
  parm/postcntrl_gfs_flux.xml
  parm/postcntrl_gfs_flux_f00.xml
  parm/postcntrl_gfs_two.xml
  parm/postxconfig-NT-GFS-ANL.txt
  parm/postxconfig-NT-GFS-F00-TWO.txt
  parm/postxconfig-NT-GFS-F00.txt
  parm/postxconfig-NT-GFS-FLUX-F00.txt
  parm/postxconfig-NT-GFS-FLUX.txt
  parm/postxconfig-NT-GFS-TWO.txt
  parm/postxconfig-NT-GFS.txt
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/DEALLOCATE.f
  sorc/ncep_post.fd/INITPOST_GFS_NETCDF_PARA.f
  sorc/ncep_post.fd/RQSTFLD.F
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/VRBLS2D_mod.f
Labels: Baseline Change, GFSV17/GEFSV13, New input data required

#388 added link to built docs on gh-pages branch in README
  README.md
Labels: enhancement, Ready for Review, No Baseline Change

#390 updated Doxyfile, turned on warnings
  docs/Doxyfile.in
Labels: enhancement, Ready for Review, No Baseline Change

#394 Updates for Himawari-8
  parm/params_grib2_tbl_new
  parm/params_grib2_tbl_new.text
  sorc/ncep_post.fd/CALRAD_WCLOUD_newcrtm.f
Labels: enhancement, Ready for Review, No Baseline Change

#396 Fixes for 1000 mb HGT corrupted at RRFS 3KM parallel run.
  VERSION
  sorc/ncep_post.fd/MDL2P.f
  sorc/ncep_post.fd/SLP_new.f
Labels: bug, Ready for Review, Baseline Change
