Repository NOAA-EMC/UPP, pull requests merged in 2022-10, with the labels that each got.

#567 Update 14 SPC analysis variables
  parm/3drtma_postcntrl.xml
  parm/fv3lam_rrfs.xml
  parm/post_avblflds.xml
  parm/postxconfig-NT-3drtma.txt
  parm/postxconfig-NT-fv3lam_rrfs.txt
  sorc/ncep_post.fd/MISCLN.f
Labels: Ready for Review, Baseline Change, RRFS, 3DRTMA

#545 Account for left-mover in SH in SRH
  sorc/ncep_post.fd/CALHEL.f
Labels: enhancement, Ready for Review, Baseline Change, GFSV17/GEFSV13, HAFS

#561 Implement the capability to process chemical model NETCDF output and UFS-Aerosols model output
  parm/makefile
  parm/optics_luts_DUST_nasa.dat
  parm/optics_luts_SALT_nasa.dat
  parm/optics_luts_SOOT_nasa.dat
  parm/optics_luts_SUSO_nasa.dat
  parm/optics_luts_WASO_nasa.dat
  parm/post_avblflds.xml
  parm/postcntrl_ufs_aerosol.xml
  parm/postcntrl_ufs_aerosol_f00.xml
  parm/postxconfig-NT-UFS-aerosol-F00.txt
  parm/postxconfig-NT-UFS-aerosol.txt
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/CTLBLK.f
  sorc/ncep_post.fd/DEALLOCATE.f
  sorc/ncep_post.fd/FDLVL.f
  sorc/ncep_post.fd/INITPOST_GFS_NEMS_MPIIO.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MDL2P.f
  sorc/ncep_post.fd/MDLFLD.f
  sorc/ncep_post.fd/MISCLN.f
  sorc/ncep_post.fd/MPI_FIRST.f
  sorc/ncep_post.fd/VRBLS2D_mod.f
  sorc/ncep_post.fd/VRBLS4D_mod.f
  sorc/ncep_post.fd/WRFPOST.f
Labels: Ready for Review, No Baseline Change, GFSV17/GEFSV13

#570 NOAA GSL updates to output new simulated satellite brightness temps
  parm/fv3lam_rrfs.xml
  parm/params_grib2_tbl_new
  parm/params_grib2_tbl_new.text
  parm/post_avblflds.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
  sorc/ncep_post.fd/CALRAD_WCLOUD_newcrtm.f
Labels: Ready for Review, No Baseline Change, RRFS

#578 Add 0-1km helicity as GFS product, unify visibility calculation for FV3 based models, two bug fixes
  parm/global_1x1_paramlist_g2
  parm/global_1x1_paramlist_g2.f000
  parm/postcntrl_gfs.xml
  parm/postcntrl_gfs_f00.xml
  parm/postcntrl_gfs_f00_two.xml
  parm/postcntrl_gfs_two.xml
  parm/postxconfig-NT-GFS-F00-TWO.txt
  parm/postxconfig-NT-GFS-F00.txt
  parm/postxconfig-NT-GFS-TWO.txt
  parm/postxconfig-NT-GFS.txt
  sorc/ncep_post.fd/MDLFLD.f
Labels: bug, Baseline Change, GFSV17/GEFSV13

#579 Add nitrate AOD look-up table and AOD calculation for UFS-Aerosols model
  parm/global_1x1_paramlist_g2.f000_chem
  parm/global_1x1_paramlist_g2_chem
  parm/optics_luts_NITR_nasa.dat
  parm/post_avblflds.xml
  parm/postcntrl_ufs_aerosol.xml
  parm/postcntrl_ufs_aerosol_f00.xml
  parm/postxconfig-NT-UFS-aerosol-F00.txt
  parm/postxconfig-NT-UFS-aerosol.txt
  sorc/ncep_post.fd/CLDRAD.f
Labels: Ready for Review, No Baseline Change, GFSV17/GEFSV13

#586 update poc
  docs/AddNewVariable.rst
Labels: documentation, Ready for Review, No Baseline Change, Clean up
