Repository NOAA-EMC/UPP, pull requests merged in 2022-06, with the labels that each got.

#517 Documentation/run script updates for 2D decomposition
  docs/AddNewVariable.rst
  docs/CodeOverview.rst
  docs/InputsOutputs.rst
  docs/Running.rst
  scripts/run_upp
Labels: documentation, No Baseline Change

#516 Fix of ABSV computation in RRFS
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/UPP_MATH.f
  sorc/ncep_post.fd/UPP_PHYSICS.f
Labels: Ready for Review, Baseline Change, RRFS, HAFS

#523 read in dx/dy instead of calculating them
  sorc/ncep_post.fd/grib2_module.f
Labels: Ready for Review, No Baseline Change, HAFS

#527 Upgrade intel/impi version to 2022.1.2 on Hera and Orion
  modulefiles/hera
  modulefiles/hera.lua
  modulefiles/orion
  modulefiles/orion.lua
Labels: enhancement, Ready for Review
