Repository NOAA-EMC/UPP, pull requests merged in 2022-02, with the labels that each got.

#444 Exception handling if anl input not found (#443)
  scripts/exgdas_atmos_nceppost.sh
  scripts/exgfs_atmos_nceppost.sh
Labels: Ready for Review, No Baseline Change, GFSV17/GEFSV13

#441 Update regional FV3 read interface with parallel netcdf read
  sorc/ncep_post.fd/INITPOST_GFS_NETCDF_PARA.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
Labels: Ready for Review, No Baseline Change, RRFS, HAFS

#445 Update documentation to reflect updates to develop (fortran namelist/RQSTFLD removal)
  docs/AddNewVariable.rst
  docs/InputsOutputs.rst
Labels: documentation, Ready for Review, No Baseline Change

#448 Make executable directory name switchable with exec
  CMakeLists.txt
  README.md
  sorc/ncep_post.fd/CMakeLists.txt
Labels: enhancement, Ready for Review, No Baseline Change, RRFS
