Repository NOAA-EMC/UPP, pull requests merged in 2023-03, with the labels that each got.

#646 bug fixes needed for running with libIFI
  .github/workflows/intel.yml
  sorc/ncep_post.fd/SURFCE.f
  tests/compile_upp.sh
Labels: bug, Ready for Review, No Baseline Change, RRFS

#643 Lightning threat indexes calculated inside model
  parm/fv3lam.xml
  parm/fv3lam_post_avblflds.xml
  parm/fv3lam_rrfs.xml
  parm/post_avblflds.xml
  parm/postxconfig-NT-3drtma.txt
  parm/postxconfig-NT-fv3lam.txt
  parm/postxconfig-NT-fv3lam_rrfs.txt
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MDL2AGL.f
Labels: Ready for Review, Baseline Change, RRFS, 3DRTMA

#652 Fix out-of-bounds access in U10 & V10 calculation, and add some missing halo exchanges
  sorc/ncep_post.fd/MDLFLD.f
  sorc/ncep_post.fd/UPP_MATH.f
Labels: bug, Ready for Review, No Baseline Change

#640 Add coarse dust product for RRFS
  parm/fv3lam_rrfs.xml
  parm/post_avblflds.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/CALPW.f
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/DEALLOCATE.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MDL2P.f
  sorc/ncep_post.fd/MDLFLD.f
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/VRBLS2D_mod.f
  sorc/ncep_post.fd/VRBLS4D_mod.f
Labels: Ready for Review, No Baseline Change, RRFS

#655 Changes needed for ufs-weather-model IFI regression tests on Acorn
  modulefiles/wcoss2_a.lua
  parm/fv3lam.xml
  parm/postxconfig-NT-fv3lam.txt
Labels: Ready for Review, Baseline Change, RRFS

#659 Add updated CALGUST/CALHEL htmls to gh-pages
  CALGUST_8f.html
  CALGUST_8f.js
  CALGUST_8f_source.html
  CALHEL_8f.html
  CALHEL_8f.js
  CALHEL_8f_source.html
Labels: documentation

#663 Update Documentation for GFSPOSTSIG.F
  sorc/ncep_post.fd/GFSPOSTSIG.F
Labels: documentation, Ready for Review, No Baseline Change

#673 `CALSLR_ROEBBER`: Instead of calling BOUND incorrectly, use min and max
  sorc/ncep_post.fd/IFI.F
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/UPP_PHYSICS.f
Labels: bug, Ready for Review, No Baseline Change

#661 Transition the U Utah SLR algorithm to UPP
  sorc/ncep_post.fd/CTLBLK.f
  sorc/ncep_post.fd/MDL2P.f
  sorc/ncep_post.fd/UPP_PHYSICS.f
  sorc/ncep_post.fd/WRFPOST.f
Labels: Ready for Review, No Baseline Change, GFSV17, RRFS

#666 Write all non-fatal messages to stdout instead stderr
  sorc/ncep_post.fd/CALWXT_RAMER.f
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/COLLECT_LOC.f
  sorc/ncep_post.fd/EXCH.f
  sorc/ncep_post.fd/EXCH_c_float.f
  sorc/ncep_post.fd/GFIP3.f
  sorc/ncep_post.fd/GFSPOST.F
  sorc/ncep_post.fd/GFSPOSTSIG.F
  sorc/ncep_post.fd/IFI.F
  sorc/ncep_post.fd/INITPOST_GFS_NEMS_MPIIO.f
  sorc/ncep_post.fd/INITPOST_NEMS.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MDL2THANDPV.f
  sorc/ncep_post.fd/MDLFLD.f
  sorc/ncep_post.fd/MISCLN.f
  sorc/ncep_post.fd/MPI_FIRST.f
  sorc/ncep_post.fd/PROCESS.f
  sorc/ncep_post.fd/READ_xml.f
  sorc/ncep_post.fd/SETUP_SERVERS.f
  sorc/ncep_post.fd/SET_LVLSXML.f
  sorc/ncep_post.fd/SET_OUTFLDS.f
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/TABLE.f
  sorc/ncep_post.fd/WRFPOST.f
  sorc/ncep_post.fd/grib2_module.f
  sorc/ncep_post.fd/xml_perl_data.f
Labels: enhancement, Ready for Review, No Baseline Change

#675 Read RRFS effective radii
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/CALRAD_WCLOUD_newcrtm.f
  sorc/ncep_post.fd/DEALLOCATE.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MPI_FIRST.f
  sorc/ncep_post.fd/VRBLS3D_mod.f
Labels: Ready for Review, No Baseline Change, RRFS

#678 fixed a bug in reading aerosol diagnostic outputs from GEFS-Aerosols
  sorc/ncep_post.fd/INITPOST_GFS_NEMS_MPIIO.f
Labels: Ready for Review, No Baseline Change, GEFSV13
