Repository NOAA-EMC/UPP, pull requests merged in 2023-07, with the labels that each got.

#722 [develop] Updates to Users Guide and Tables
  README.md
  docs/Acknowledgments.rst
  docs/AddNewVariable.rst
  docs/CodeOverview.rst
  docs/Glossary.rst
  docs/InputsOutputs.rst
  docs/Installation.rst
  docs/Introduction.rst
  docs/Regridding.rst
  docs/Running.rst
  docs/UFS_unified_variables_table.csv
  docs/UFS_unified_variables_table.rst
  docs/UPP_GRIB2_Table.csv
  docs/UPP_GRIB2_Table_byID.csv
  docs/UPP_GRIB2_Table_byID.rst
  docs/_static/theme_overrides.css
  docs/conf.py
  docs/index.rst
  parm/post_avblflds.xml
  scripts/run_upp
Labels: documentation, Ready for Review, No Baseline Change

#740 Updating GRIB2 labeling for MSTAV, and adding SOILL on 9 RUC levels.
  parm/fv3lam_rrfs.xml
  parm/post_avblflds.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
  sorc/ncep_post.fd/INITPOST_NETCDF.f
Labels: Baseline Change, RRFS, 3DRTMA

#746 Bugfix on `-prefix` and build flexibility for UPP.
  tests/compile_upp.sh
Labels: enhancement, Ready for Review, No Baseline Change

#737 [develop]: Update most remaining documentation files
  docs/Doxyfile.in
  sorc/ncep_post.fd/CALHEL2.f
  sorc/ncep_post.fd/CALHEL3.f
  sorc/ncep_post.fd/CALMICT.f
  sorc/ncep_post.fd/CALPBL.f
  sorc/ncep_post.fd/CALPBLREGIME.f
  sorc/ncep_post.fd/CALPW.f
  sorc/ncep_post.fd/CALRAD_WCLOUD_newcrtm.f
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/COLLECT.f
  sorc/ncep_post.fd/COLLECT_LOC.f
  sorc/ncep_post.fd/CTLBLK.f
  sorc/ncep_post.fd/EXCH.f
  sorc/ncep_post.fd/FDLVL.f
  sorc/ncep_post.fd/GFIP3.f
  sorc/ncep_post.fd/GPVS.f
  sorc/ncep_post.fd/GRIDSPEC.f
  sorc/ncep_post.fd/INITPOST_GFS_NEMS_MPIIO.f
  sorc/ncep_post.fd/INITPOST_NEMS.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MDL2P.f
  sorc/ncep_post.fd/MPI_FIRST.f
  sorc/ncep_post.fd/PMICRPH.f
  sorc/ncep_post.fd/PROCESS.f
  sorc/ncep_post.fd/SELECT_CHANNELS.f
  sorc/ncep_post.fd/SMOOTH.f
  sorc/ncep_post.fd/WRFPOST.f
  sorc/ncep_post.fd/xml_perl_data.f
Labels: documentation, Ready for Review, No Baseline Change

#750 Clean out lagacy fv3lam control file and bug fix of tke initialization
  parm/README.make_flatfile
  parm/fv3lam.xml
  parm/fv3lam_post_avblflds.xml
  parm/makefile
  parm/params_grib2_tbl_new_dtc
  parm/postcntrl.xml
  parm/postcntrl_wrf.xml
  parm/postxconfig-NT-WRF.txt
  parm/postxconfig-NT-fv3lam.txt
  parm/postxconfig-NT-fv3lam_rrfs.txt
  parm/postxconfig-NT.txt
  sorc/ncep_post.fd/INITPOST_NETCDF.f
Labels: bug, remove legacy
