Repository NOAA-EMC/UPP, pull requests merged in 2023-09, with the labels that each got.

#704 adding new products to RRFS from legacy models
  parm/fv3lam_rrfs.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
Labels: Ready for Review, Baseline Change, RRFS

#785 Compile on GAEA C5 partition
  modulefiles/gaea.lua
  modulefiles/gaea_c5.lua
  tests/compile_upp.sh
  tests/detect_machine.sh
Labels: enhancement, Ready for Review, No Baseline Change

#783 Remove old icing severity (ICSEV) from RRFS control file
  parm/fv3lam_rrfs.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
Labels: Ready for Review, Baseline Change, RRFS

#788 simpler parm/makefile
  parm/makefile
Labels: enhancement, Ready for Review, No Baseline Change

#771 Eliminate artificial supercooled water (rain and cloud) on pressure levels
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MDL2P.f
Labels: Ready for Review, Baseline Change, GFSV17, RRFS

#793 rename gaea_c5 to gaea-c5
  modulefiles/gaea-c5.lua
  tests/detect_machine.sh
Labels: bug, Ready for Review, No Baseline Change

#791 RRFS cloud base/top: diagnose using cloud fraction
  sorc/ncep_post.fd/CLDRAD.f
Labels: Ready for Review, Baseline Change, RRFS, HAFS
