Repository NOAA-EMC/UPP, pull requests merged in 2023-04, with the labels that each got.

#681 Update documentation for MSFPS.f, NGMFLD.f, OTLFT.f, OTLIFT.f, and ZENSUN.f
  sorc/ncep_post.fd/MSFPS.f
  sorc/ncep_post.fd/NGMFLD.f
  sorc/ncep_post.fd/OTLFT.f
  sorc/ncep_post.fd/OTLIFT.f
  sorc/ncep_post.fd/ZENSUN.f
Labels: documentation, Ready for Review, No Baseline Change

#682 MISCLN.f updated to resolve issues in generating SPC fields using RRF…
  sorc/ncep_post.fd/MISCLN.f
Labels: Ready for Review, Baseline Change, 3DRTMA

#684 Update to EPIC hpc-stack location
  modulefiles/hera.lua
  modulefiles/orion.lua
Labels: enhancement, Ready for Review

#688 Add namelist options for chemical models
  parm/postcntrl_ccpp_chem.xml
  parm/postcntrl_ccpp_chem_f00.xml
  parm/postxconfig-NT-CCPP-CHEM-F00.txt
  parm/postxconfig-NT-CCPP-CHEM.txt
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/CTLBLK.f
  sorc/ncep_post.fd/DEALLOCATE.f
  sorc/ncep_post.fd/FDLVL.f
  sorc/ncep_post.fd/INITPOST_GFS_NEMS_MPIIO.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MDL2P.f
  sorc/ncep_post.fd/MDLFLD.f
  sorc/ncep_post.fd/WRFPOST.f
Labels: Ready for Review, No Baseline Change, GEFSV13

#689 Add updated MSFPS.f, NGMFLD.f, OTLFT.f, OTLIFT.f, and ZENSUN.f htmls to gh-pages
  MSFPS_8f.html
  MSFPS_8f.js
  MSFPS_8f_source.html
  NGMFLD_8f.html
  NGMFLD_8f.js
  NGMFLD_8f_source.html
  OTLFT_8f.html
  OTLFT_8f.js
  OTLFT_8f_source.html
  OTLIFT_8f.html
  OTLIFT_8f.js
  OTLIFT_8f_source.html
  ZENSUN_8f.html
  ZENSUN_8f_source.html
Labels: documentation

#692 Cleaning up legacy 3DRTMA control file based on HRRR-based UPP templates
  parm/3drtma_postcntrl.xml
  parm/PostXMLPreprocessor.pl
  parm/makefile
  parm/postxconfig-NT-3drtma.txt
  parm/postxconfig-NT-GEFS-F00.txt
  parm/postxconfig-NT-GEFS.txt
Labels: Ready for Review, No Baseline Change, 3DRTMA, Clean up

#693 Changes to output variables at 160 m and 320 m above ground
  parm/fv3lam_rrfs.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/CTLBLK.f
  sorc/ncep_post.fd/DEALLOCATE.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/VRBLS2D_mod.f
Labels: Ready for Review, Baseline Change, RRFS, 3DRTMA

#695 Enabling GSL p-type, winter QPF and buckets, and lightning threat indices for RRFS
  parm/fv3lam_rrfs.xml
  parm/post_avblflds.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/SURFCE.f
Labels: Ready for Review, Baseline Change, RRFS, 3DRTMA

#696 Update documentation for several UPP files
  sorc/ncep_post.fd/CTLBLK.f
  sorc/ncep_post.fd/DEWPOINT.f
  sorc/ncep_post.fd/EXCH_c_float.f
  sorc/ncep_post.fd/FILL_PSETFLD.f
  sorc/ncep_post.fd/FRZLVL.f
  sorc/ncep_post.fd/FRZLVL2.f
  sorc/ncep_post.fd/GET_BITS.f
  sorc/ncep_post.fd/GFIP3.f
  sorc/ncep_post.fd/GFSPOST.F
  sorc/ncep_post.fd/LFMFLD.f
  sorc/ncep_post.fd/LFMFLD_GFS.f
  sorc/ncep_post.fd/MDL2STD_P.f
  sorc/ncep_post.fd/MDL2THANDPV.f
  sorc/ncep_post.fd/PARA_RANGE.f
  sorc/ncep_post.fd/SCLFLD.f
  sorc/ncep_post.fd/SELECT_CHANNELS.f
  sorc/ncep_post.fd/SMOOTH.f
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/UPP_MATH.f
  sorc/ncep_post.fd/UPP_PHYSICS.f
  sorc/ncep_post.fd/kinds_mod.F
  sorc/ncep_post.fd/native_endianness.f
  sorc/ncep_post.fd/retrieve_index.f
Labels: documentation, Ready for Review, No Baseline Change
