Repository NOAA-EMC/UPP, pull requests merged in 2024-09, with the labels that each got.

#1029 Updates to support MPAS applications (RRFS and HFIP)
  parm/hfip_postcntrl.xml
  parm/postxconfig-NT-hfip.txt
  parm/postxconfig-NT-rrfs_mpas.txt
  parm/rrfs_mpas_postcntrl.xml
  sorc/ncep_post.fd/INITPOST_MPAS.F
  sorc/ncep_post.fd/WRFPOST.F
  sorc/ncep_post.fd/getIVariableN.f
  sorc/ncep_post.fd/getVariable.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, MPAS, Ready for commit queue

#1037 Enhancements for MPAS applications
  parm/postxconfig-NT-rrfs_mpas.txt
  parm/rrfs_mpas_postcntrl.xml
  sorc/ncep_post.fd/INITPOST_MPAS.F
  sorc/ncep_post.fd/SURFCE.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, MPAS, Ready for commit queue

#1044 Per AWC new request, adjust additional levels for WAFS icing and turbulence
  parm/postcntrl_gfs_wafs.xml
  parm/postxconfig-NT-GFS-WAFS.txt
Labels: Ready for Review, WAFSV7

#1042 Adding SREF products to GEFS v13 (UPP #1013).
  parm/gefs/postcntrl_gefs.xml
  parm/gefs/postxconfig-NT-gefs.txt
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, GEFSV13, Ready for commit queue

#1048 Bump up w3emc and ip versions on WCOSS2.
  modulefiles/wcoss2.lua
Labels: enhancement, Ready for Review, No Baseline Change, Ready for commit queue

#1049 [develop]: Update user_guide.md to include links to other doc versions
  doc/user_guide.md
Labels: documentation, No Baseline Change, Ready for commit queue

#1001 Support IntelLLVM compiler
  CMakeLists.txt
  sorc/ncep_post.fd/CMakeLists.txt
Labels: enhancement, Ready for Review, Ready for commit queue
