Repository NOAA-EMC/UPP, pull requests merged in 2024-10, with the labels that each got.

#1034 Make UPP works with Rocky 8 on CSPs
  modulefiles/noaacloud.lua
Labels: enhancement, Ready for Review, Ready for commit queue

#1054 RRFS-MPAS: Provide TSOIL and SOILW (9 levels) in native-level GRIB2 files
  parm/postxconfig-NT-rrfs_mpas.txt
  parm/rrfs_mpas_postcntrl.xml
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, MPAS, Ready for commit queue

#1052 Add aerosol fields in the gefs UPP control files
  fix/hires_micro_lookup.dat
  fix/nam_micro_lookup.dat
  fix/rap_micro_lookup.dat
  parm/gefs/postcntrl_gefs.xml
  parm/gefs/postcntrl_gefs_f00.xml
  parm/gefs/postxconfig-NT-gefs-f00.txt
  parm/gefs/postxconfig-NT-gefs.txt
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, GEFSV13, Ready for commit queue

#1060 Add gefs inline post itag file
  parm/gefs/post_itag_gefs128
  parm/gfs/post_itag_gfs128
  parm/gfs/post_itag_gfs65
  parm/gfs/post_tag_gfs128
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, GFSV17, GEFSV13, Ready for commit queue

#1066 new sfs output for global-workflow
  parm/sfs/postcntrl_sfs.xml
  parm/sfs/postxconfig-NT-sfs.txt
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, SFSV1, Ready for commit queue

#1070 Update module file after Gaea-C5 OS upgrade
  modulefiles/gaeac5.lua
  modulefiles/gaeac6.lua
  tests/detect_machine.sh
Labels: Ready for Review, No Baseline Change, EPIC Support Requested, Ready for commit queue

#1069 MPAS applications: fixes for absolute vorticity and surface latent-heat flux
  sorc/ncep_post.fd/INITPOST_MPAS.F
  sorc/ncep_post.fd/UPP_PHYSICS.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, MPAS, Ready for commit queue

#1075 Reduce the printouts for GEFS processing.
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/grib2_module.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, GEFSV13, Ready for commit queue

#1076 Change gtg_algo inputs (MDLFLD.f)
  sorc/ncep_post.fd/MDLFLD.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review, No Baseline Change, Ready for commit queue

#1080 Unify iSF_SURFACE_PHYSICS
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/WRFPOST.F
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review
