Repository NOAA-EMC/UPP, pull requests merged in 2024-04, with the labels that each got.

#908 Add surface albedo, accumulated snow melt, and total soil moisture output in RRFS
  parm/fv3lam_rrfs.xml
  parm/post_avblflds.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
  sorc/ncep_post.fd/CALVIS_GSD.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/SURFCE.f
Labels: Ready for Review, Baseline Change, RRFS

#918 Add LTNG in PRSLEV dataset of RRFS
  parm/fv3lam_rrfs.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
Labels: Ready for Review, Baseline Change, RRFS

#911 Add BUILD_WITH_NEMSIO build option to allow building UPP without nemsio
  CMakeLists.txt
  sorc/ncep_post.fd/CMakeLists.txt
  sorc/ncep_post.fd/WRFPOST.F
  tests/compile_upp.sh
Labels: enhancement, Ready for Review, No Baseline Change

#920 Remove the detection of Jet/Centos7 nodes
  modulefiles/jet_c.lua
  tests/detect_machine.sh
Labels: bug, Ready for Review, No Baseline Change

#922 Correct total soil moisture from SOIMOI to CISOIM
  parm/post_avblflds.xml
  parm/postcntrl_gfs_f00_two.xml
  parm/postcntrl_gfs_flux.xml
  parm/postcntrl_gfs_flux_f00.xml
  parm/postcntrl_gfs_two.xml
  parm/postxconfig-NT-GFS-F00-TWO.txt
  parm/postxconfig-NT-GFS-FLUX-F00.txt
  parm/postxconfig-NT-GFS-FLUX.txt
  parm/postxconfig-NT-GFS-TWO.txt
  sorc/ncep_post.fd/CMakeLists.txt
Labels: bug, Ready for Review, Baseline Change, GFSV17

#926 For RRFS, change the mnemonics of column max of EDPARM to MXEDPRM
  parm/fv3lam_rrfs.xml
  parm/post_avblflds.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
  sorc/ncep_post.fd/MISCLN.f
Labels: Ready for Review, RRFS

#915 Bug fix for blowing snow effect on visibility
  sorc/ncep_post.fd/CALVIS_GSD.f
Labels: Ready for Review, Baseline Change, RRFS

#930 Remove dependency on sfcio and use sigio only when nemsio is enabled
  CMakeLists.txt
  modulefiles/upp_common.lua
  modulefiles/wcoss2.lua
  sorc/ncep_post.fd/CMakeLists.txt
Labels: enhancement, Ready for Review, No Baseline Change

#932 turn on doxygen build in CI
  .github/workflows/gcc.yml
  CMakeLists.txt
  doc/Doxyfile.in
Labels: enhancement, Ready for Review, No Baseline Change

#937 Add flight height SPFH and PRES in the RRFS product list
  parm/fv3lam_rrfs.xml
  parm/postxconfig-NT-fv3lam_rrfs.txt
Labels: Ready for Review, Baseline Change, RRFS

#934 add module for AWS
  modulefiles/noaacloud.lua
Labels: enhancement, Ready for Review, No Baseline Change

#938 RRFS updates
  parm/README.make_flatfile
  parm/makefile
  parm/post_avblflds.xml
  parm/postxconfig-NT-rrfs.txt
  parm/rrfs_postcntrl.xml
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/CALPW.f
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MDL2P.f
  sorc/ncep_post.fd/MDLFLD.f
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/VRBLS2D_mod.f
  sorc/ncep_post.fd/VRBLS4D_mod.f
Labels: Ready for Review, Baseline Change, RRFS
