Repository NOAA-EMC/UPP, pull requests merged in 2024-08, with the labels that each got.

#1011 Enable template 4-49 to obtain aerosol ensemble information
  ci/spack.yaml
  modulefiles/upp_common.lua
  modulefiles/wcoss2.lua
  sorc/ncep_post.fd/grib2_module.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review, GEFSV13

#1007 Sample PR for testing
  ci/Jenkinsfile
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review, No Baseline Change

#1023 [develop]: Turn on WARN_AS_ERROR for Doxygen Documentation Builds
  .github/CODEOWNERS
  .github/workflows/intel.yml
  doc/Doxyfile.in
Labels: documentation, enhancement, Ready for Review, No Baseline Change

#1021 Enable output of VEGMIN/VEGMAX
  parm/postxconfig-NT-rrfs.txt
  parm/rrfs_postcntrl.xml
  sorc/ncep_post.fd/INITPOST_NETCDF.f
Labels: Ready for Review, RRFS

#1018 Updates to support UPP use with MPAS
  parm/hfip_postcntrl.xml
  parm/postxconfig-NT-hfip.txt
  parm/postxconfig-NT-rrfs_mpas.txt
  parm/rrfs_mpas_postcntrl.xml
  sorc/ncep_post.fd/CMakeLists.txt
  sorc/ncep_post.fd/INITPOST_MPAS.F
  sorc/ncep_post.fd/WRFPOST.F
  sorc/ncep_post.fd/getIVariableN.f
  sorc/ncep_post.fd/getVariable.f
  sorc/ncep_post.fd/io_int_stubs.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, MPAS

#1027 Update Jet modulefile spack-stack path
  modulefiles/jet.lua
Labels: enhancement, Ready for Review, Ready for commit queue

#1019 Add 6-hrly max winds at 10m to SFS
  parm/sfs/postcntrl_sfs.xml
  parm/sfs/postxconfig-NT-sfs.txt
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/SURFCE.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, SFSV1, Ready for commit queue
