Repository NOAA-EMC/UPP, pull requests merged in 2024-11, with the labels that each got.

#1083 Correct spack-stack path for Gaea-C6
  modulefiles/gaeac6.lua
Labels: enhancement, Ready for Review, No Baseline Change

#1085 Add max wind variables and AI/ML variables for GEFS
  parm/gefs/postcntrl_gefs.xml
  parm/gefs/postxconfig-NT-gefs.txt
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, Ready for commit queue

#1062 Spack Stack 1.8.0
  CMakeLists.txt
  README.md
  ci/rt.sh
  ci/spack.yaml
  doc/UserGuide/BuildingRunningTesting/BuildingUPP.rst
  modulefiles/gaeac5.lua
  modulefiles/hera.lua
  modulefiles/hercules.lua
  modulefiles/orion.lua
  modulefiles/upp_common.lua
  sorc/ncep_post.fd/CMakeLists.txt
  sorc/ncep_post.fd/GFSPOSTSIG.F
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review

#1088 RRFS-MPAS applications: add several fields to output; remove "imp_physics" logic from INITPOST_MPAS
  parm/postxconfig-NT-rrfs_mpas.txt
  parm/rrfs_mpas_postcntrl.xml
  sorc/ncep_post.fd/INITPOST_MPAS.F
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, MPAS, Ready for commit queue

#1092 Pick up module version changes from NCO based on WAFSv7.0.0
  modulefiles/post/post_wcoss2.lua
Labels: Ready for Review, WAFSV7, Ready for commit queue

#1100 use @v4 of cache & checkout actions
  .github/workflows/gcc.yml
  .github/workflows/intel.yml
Labels: enhancement, Ready for Review, Ready for commit queue
