Repository NOAA-EMC/UPP, pull requests merged in 2024-07, with the labels that each got.

#984 Read bucket either as an integer or float
  sorc/ncep_post.fd/CALGUST.f
  sorc/ncep_post.fd/CALUPDHEL.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MDLFLD.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review, No Baseline Change

#965 [develop]: Add Doxygen variable definitions to modules
  doc/Doxyfile.in
  doc/UserGuide/tables/UFS_unified_variables_table.csv
  doc/user_guide.md
  sorc/ncep_post.fd/BNDLYR.f
  sorc/ncep_post.fd/BOUND.f
  sorc/ncep_post.fd/CALDWP.f
  sorc/ncep_post.fd/CALGUST.f
  sorc/ncep_post.fd/CALHEL.f
  sorc/ncep_post.fd/CMASSI.f
  sorc/ncep_post.fd/CTLBLK.f
  sorc/ncep_post.fd/FRZLVL2.f
  sorc/ncep_post.fd/GFIP3.f
  sorc/ncep_post.fd/GFSPOSTSIG.F
  sorc/ncep_post.fd/IFI.F
  sorc/ncep_post.fd/LOOKUP.f
  sorc/ncep_post.fd/MASKS_mod.f
  sorc/ncep_post.fd/MISCLN.f
  sorc/ncep_post.fd/OTLFT.f
  sorc/ncep_post.fd/PARA_RANGE.f
  sorc/ncep_post.fd/READ_xml.f
  sorc/ncep_post.fd/RHGRD.f
  sorc/ncep_post.fd/RQSTFLD.f
  sorc/ncep_post.fd/SET_LVLSXML.f
  sorc/ncep_post.fd/SET_OUTFLDS.f
  sorc/ncep_post.fd/SOIL_mod.f
  sorc/ncep_post.fd/TRPAUS.f
  sorc/ncep_post.fd/UPP_PHYSICS.f
  sorc/ncep_post.fd/VRBLS2D_mod.f
  sorc/ncep_post.fd/VRBLS3D_mod.f
  sorc/ncep_post.fd/VRBLS4D_mod.f
  sorc/ncep_post.fd/WRFPOST.F
  sorc/ncep_post.fd/ZENSUN.f
  sorc/ncep_post.fd/cuparm.f
  sorc/ncep_post.fd/grib2_module.f
  sorc/ncep_post.fd/gtg_filter.F90
  sorc/ncep_post.fd/gtg_indices.F90
  sorc/ncep_post.fd/gtg_read_config.F90
  sorc/ncep_post.fd/intio_tags.f
  sorc/ncep_post.fd/machine.f
  sorc/ncep_post.fd/params.F
  sorc/ncep_post.fd/physcons.f
  sorc/ncep_post.fd/svptbl.f
  sorc/ncep_post.fd/wrf_io_flags.f
  sorc/ncep_post.fd/xml_perl_data.f
  tests/logs/rt.log.HERA
Labels: documentation, Ready for Review, No Baseline Change

#993 Correct failing to build UPP on Gaea-C5
  modulefiles/gaea.lua
Labels: bug, Ready for Review, No Baseline Change

#994 [develop]: Update requirements files
  doc/UserGuide/requirements.in
  doc/UserGuide/requirements.txt
  tests/logs/rt.log.HERA
Labels: documentation, Ready for Review, Clean up

#990 Relocate gfs/gefs/sfs control files
  .gitignore
  CMakeLists.txt
  parm/CMakeLists.txt
  parm/gefs/postcntrl_gefs.xml
  parm/gefs/postcntrl_gefs_aerosol.xml
  parm/gefs/postcntrl_gefs_aerosol_f00.xml
  parm/gefs/postcntrl_gefs_chem.xml
  parm/gefs/postcntrl_gefs_f00.xml
  parm/gefs/postcntrl_gefs_wafs.xml
  parm/gefs/postxconfig-NT-gefs-aerosol.txt
  parm/gefs/postxconfig-NT-gefs-chem.txt
  parm/gefs/postxconfig-NT-gefs-f00-aerosol.txt
  parm/gefs/postxconfig-NT-gefs-f00.txt
  parm/gefs/postxconfig-NT-gefs-wafs.txt
  parm/gefs/postxconfig-NT-gefs.txt
  parm/gfs/post_tag_gfs128
  parm/gfs/post_tag_gfs65
  parm/gfs/postcntrl_gfs.xml
  parm/gfs/postcntrl_gfs_anl.xml
  parm/gfs/postcntrl_gfs_f00.xml
  parm/gfs/postcntrl_gfs_f00_two.xml
  parm/gfs/postcntrl_gfs_flux.xml
  parm/gfs/postcntrl_gfs_flux_f00.xml
  parm/gfs/postcntrl_gfs_goes.xml
  parm/gfs/postcntrl_gfs_two.xml
  parm/gfs/postcntrl_gfs_wafs.xml
  parm/gfs/postcntrl_gfs_wafs_anl.xml
  parm/gfs/postcntrl_gfs_wafs_ext.xml
  parm/gfs/postxconfig-NT-gfs-anl.txt
  parm/gfs/postxconfig-NT-gfs-f00-two.txt
  parm/gfs/postxconfig-NT-gfs-f00.txt
  parm/gfs/postxconfig-NT-gfs-flux-f00.txt
  parm/gfs/postxconfig-NT-gfs-flux.txt
  parm/gfs/postxconfig-NT-gfs-goes.txt
  parm/gfs/postxconfig-NT-gfs-two.txt
  parm/gfs/postxconfig-NT-gfs-wafs-anl.txt
  parm/gfs/postxconfig-NT-gfs-wafs-ext.txt
  parm/gfs/postxconfig-NT-gfs-wafs.txt
  parm/gfs/postxconfig-NT-gfs.txt
  parm/makefile
  parm/postcntrl_gfs_goes.xml-new
  parm/sfs/postcntrl_sfs.xml
  parm/sfs/postxconfig-NT-sfs.txt
  sorc/ncep_post.fd/RQSTFLD.f
  sorc/ncep_post.fd/xml_perl_data.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review, No Baseline Change, GFSV17, GEFSV13, SFSV1

#1004 Add more levels of icing and turbulence to WAFS UPP control file
  parm/postcntrl_gfs_wafs.xml
  parm/postxconfig-NT-GFS-WAFS.txt
Labels: Ready for Review, WAFSV7
