Repository NOAA-EMC/UPP, pull requests merged in 2024-05, with the labels that each got.

#945 Build UPP on Gaea
  modulefiles/gaea.lua
Labels: enhancement, Ready for Review, No Baseline Change

#941 Additional RT log information
  ci/rt.sh
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review, No Baseline Change

#947 Updates to the GSL exp1 ceiling diagnostic
  sorc/ncep_post.fd/CLDRAD.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, Baseline Change, RRFS

#948 Clean up labeling for 15-min accumulated fields
  parm/makefile
  parm/post_avblflds.xml
  parm/postxconfig-NT-rrfs_subh.txt
  parm/rrfs_postcntrl_subh.xml
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/grib2_module.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, RRFS

#940 Update Namelist documentation for all namelist options
  doc/UserGuide/BuildingRunningTesting/InputsOutputs.rst
  doc/UserGuide/Reference/Glossary.rst
  tests/logs/rt.log.HERA
Labels: documentation, Ready for Review, No Baseline Change

#917 Add hourly averaged smoke PM2.5 and dust PM10
  ci/spack.yaml
  modulefiles/gaea.lua
  modulefiles/hera.lua
  modulefiles/hercules.lua
  modulefiles/jet.lua
  modulefiles/orion.lua
  modulefiles/s4.lua
  modulefiles/upp_common.lua
  modulefiles/wcoss2.lua
  parm/post_avblflds.xml
  parm/postxconfig-NT-rrfs.txt
  parm/rrfs_postcntrl.xml
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/VRBLS2D_mod.f
  sorc/ncep_post.fd/grib2_module.f
Labels: Ready for Review, Baseline Change, RRFS

#929 Updates to use GRIB2 template 4.9 for QPFFFG and QPFARI variables in RRFS
  parm/POST-XML-Library-NT.pl
  parm/post_avblflds.xml
  parm/postxconfig-NT-AQM.txt
  parm/postxconfig-NT-GEFS-F00-aerosol.txt
  parm/postxconfig-NT-GEFS-F00.txt
  parm/postxconfig-NT-GEFS-aerosol.txt
  parm/postxconfig-NT-GEFS.txt
  parm/postxconfig-NT-GFS-ANL.txt
  parm/postxconfig-NT-GFS-F00-TWO.txt
  parm/postxconfig-NT-GFS-F00.txt
  parm/postxconfig-NT-GFS-FLUX-F00.txt
  parm/postxconfig-NT-GFS-FLUX.txt
  parm/postxconfig-NT-GFS-GOES.txt
  parm/postxconfig-NT-GFS-TWO.txt
  parm/postxconfig-NT-GFS.txt
  parm/postxconfig-NT-NGAC.txt
  parm/postxconfig-NT-NMM.txt
  parm/postxconfig-NT-SFS.txt
  parm/postxconfig-NT-UFS-aerosol-F00.txt
  parm/postxconfig-NT-UFS-aerosol.txt
  parm/postxconfig-NT-hafs.txt
  parm/postxconfig-NT-hafs_nosat.txt
  parm/postxconfig-NT-hafs_sat.txt
  parm/postxconfig-NT-hrrr.txt
  parm/postxconfig-NT-rap.txt
  parm/postxconfig-NT-rrfs.txt
  parm/postxconfig-NT-rrfs_subh.txt
  sorc/ncep_post.fd/FILL_PSETFLD.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/grib2_module.f
  sorc/ncep_post.fd/xml_perl_data.f
Labels: RRFS

#957 Correct rt.sh paths
  ci/rt.sh
  modulefiles/hercules.lua
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: bug, Ready for Review, No Baseline Change
