Repository NOAA-EMC/UPP, pull requests merged in 2025-05, with the labels that each got.

#1196 Sanity checks for RRFSv1 implementation
  parm/rrfs/postxconfig-NT-refs.txt
  parm/rrfs/postxconfig-NT-refs_f00.txt
  parm/rrfs/postxconfig-NT-refs_f01.txt
  parm/rrfs/postxconfig-NT-rrfs.txt
  parm/rrfs/postxconfig-NT-rrfs_f00.txt
  parm/rrfs/postxconfig-NT-rrfs_f01.txt
  parm/rrfs/postxconfig-NT-rrfs_firewx.txt
  parm/rrfs/postxconfig-NT-rrfs_firewx_f00.txt
  parm/rrfs/postxconfig-NT-rrfs_firewx_f01.txt
  parm/rrfs/postxconfig-NT-rrfs_subh.txt
  parm/rrfs/refs_postcntrl.xml
  parm/rrfs/refs_postcntrl_f00.xml
  parm/rrfs/refs_postcntrl_f01.xml
  parm/rrfs/rrfs_postcntrl.xml
  parm/rrfs/rrfs_postcntrl_f00.xml
  parm/rrfs/rrfs_postcntrl_f01.xml
  parm/rrfs/rrfs_postcntrl_firewx.xml
  parm/rrfs/rrfs_postcntrl_firewx_f00.xml
  parm/rrfs/rrfs_postcntrl_firewx_f01.xml
  parm/rrfs/rrfs_postcntrl_subh.xml
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/TTBLEX.f
  sorc/ncep_post.fd/UPP_PHYSICS.f
  sorc/ncep_post.fd/grib2_module.f
Labels: Ready for Review, RRFS

#1200 20250507 Jesse Meng Bug fix for variable type mismatch in UPP_PHYSICS.f
  sorc/ncep_post.fd/UPP_PHYSICS.f
Labels: RRFS

#1185 Remove outdated cloud-base and cloud-top codes; remove duplicative VIL diagnostic; other refinements
  parm/hrrr_postcntrl.xml
  parm/makefile
  parm/mpas/global_mpas_postcntrl.xml
  parm/mpas/hfip_mpas_postcntrl.xml
  parm/mpas/postxconfig-NT-global_mpas.txt
  parm/mpas/postxconfig-NT-hfip_mpas.txt
  parm/mpas/postxconfig-NT-rrfs_mpas.txt
  parm/mpas/rrfs_mpas_postcntrl.xml
  parm/post_avblflds.xml
  parm/post_avblflds_raphrrr.xml
  parm/postxconfig-NT-hrrr.txt
  parm/postxconfig-NT-rap.txt
  parm/rap_postcntrl.xml
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/MDLFLD.f
  sorc/ncep_post.fd/params.F
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, Baseline Change, MPAS, Ready for commit queue

#1206 Update cloud build environment to spack-stack 1.8.0
  modulefiles/noaacloud.lua
Labels: enhancement, Ready for Review, No Baseline Change, Ready for commit queue

#1203 MPAS applications: Add hail accumulation, modify hail-size fields; fix cloud base; remove old/unused code
  parm/mpas/global_mpas_postcntrl.xml
  parm/mpas/hfip_mpas_postcntrl.xml
  parm/mpas/postxconfig-NT-global_mpas.txt
  parm/mpas/postxconfig-NT-hfip_mpas.txt
  parm/mpas/postxconfig-NT-rrfs_mpas.txt
  parm/mpas/rrfs_mpas_postcntrl.xml
  parm/params_grib2_tbl_new
  parm/params_grib2_tbl_new.text
  parm/post_avblflds.xml
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/CLDRAD.f
  sorc/ncep_post.fd/DEALLOCATE.f
  sorc/ncep_post.fd/INITPOST_MPAS.F
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/VRBLS2D_mod.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, Baseline Change, MPAS, Ready for commit queue

#1207 Updating contact info for adding a new variable
  doc/UserGuide/CustomizingTheUPP/AddNewVariable.rst
Labels: documentation, Ready for Review, Ready for commit queue

#1211 Reconfiguring noaacloud build env to not resort to system defaults
  cmake/toolchains/noaacloud.intel-toolchain.cmake
  modulefiles/noaacloud.lua
  tests/compile_upp.sh
Labels: enhancement, Ready for Review, Ready for commit queue
