Repository NOAA-EMC/UPP, pull requests merged in 2025-04, with the labels that each got.

#1179 Bug fix in HAILCAST
  sorc/ncep_post.fd/MDL2AGL.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: bug, Ready for Review, Baseline Change, RRFS, Ready for commit queue

#1163 Add PRs #1159, 1171, and 1179 into release/rrfs_v1
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/MDL2AGL.f
Labels: bug, Ready for Review, RRFS

#1177 add 19H&V to SSMS-F17 in UPP
  parm/params_grib2_tbl_new
  parm/params_grib2_tbl_new.text
  parm/post_avblflds.xml
  sorc/ncep_post.fd/CALRAD_WCLOUD_newcrtm.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review, Baseline Change, HAFS, Ready for commit queue

#1184 Use product definition template 4.1 for encoding REFS grib2 output
  parm/makefile
  parm/rrfs/postxconfig-NT-refs.txt
  parm/rrfs/postxconfig-NT-refs_f00.txt
  parm/rrfs/postxconfig-NT-refs_f01.txt
  parm/rrfs/postxconfig-NT-rrfs_firewx.txt
  parm/rrfs/postxconfig-NT-rrfs_firewx_f00.txt
  parm/rrfs/postxconfig-NT-rrfs_firewx_f01.txt
  parm/rrfs/refs_postcntrl.xml
  parm/rrfs/refs_postcntrl_f00.xml
  parm/rrfs/refs_postcntrl_f01.xml
  parm/rrfs/rrfs_postcntrl_firewx.xml
  parm/rrfs/rrfs_postcntrl_firewx_f00.xml
  parm/rrfs/rrfs_postcntrl_firewx_f01.xml
  sorc/ncep_post.fd/grib2_module.f
Labels: RRFS

#1186 Reduce RHmin in upper stratosphere and lower mesosphere to be below stratopause RH
  .github/workflows/intel.yml
  ci/jobs-dev/run_post_fv3gfs_ORION.sh
  sorc/ncep_post.fd/UPP_PHYSICS.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, Baseline Change, GFSV17, RRFS, HAFS, GEFSV13, SFSV1, Ready for commit queue

#1191 Remove experimental cloud ceiling diagnostic field from RRFS
  parm/rrfs/postxconfig-NT-refs.txt
  parm/rrfs/postxconfig-NT-refs_f00.txt
  parm/rrfs/postxconfig-NT-refs_f01.txt
  parm/rrfs/postxconfig-NT-rrfs.txt
  parm/rrfs/postxconfig-NT-rrfs_f00.txt
  parm/rrfs/postxconfig-NT-rrfs_f01.txt
  parm/rrfs/postxconfig-NT-rrfs_firewx.txt
  parm/rrfs/postxconfig-NT-rrfs_firewx_f00.txt
  parm/rrfs/postxconfig-NT-rrfs_firewx_f01.txt
  parm/rrfs/refs_postcntrl.xml
  parm/rrfs/refs_postcntrl_f00.xml
  parm/rrfs/refs_postcntrl_f01.xml
  parm/rrfs/rrfs_postcntrl.xml
  parm/rrfs/rrfs_postcntrl_f00.xml
  parm/rrfs/rrfs_postcntrl_f01.xml
  parm/rrfs/rrfs_postcntrl_firewx.xml
  parm/rrfs/rrfs_postcntrl_firewx_f00.xml
  parm/rrfs/rrfs_postcntrl_firewx_f01.xml
Labels: RRFS

#1193 Minor fix to avoid zmid=NaN in very thin layers.
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/UPP_PHYSICS.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: bug, Ready for Review
