Repository NOAA-EMC/UPP, pull requests merged in 2025-08, with the labels that each got.

#1294 Add soil and flux variables to SFS products list
  parm/sfs/postcntrl_sfs.xml
  parm/sfs/postxconfig-NT-sfs.txt
  tests/logs/rt.log.HERCULES_intel
  tests/logs/rt.log.ORION_intel
  tests/logs/rt.log.URSA_intel
  tests/logs/rt.log.URSA_intelllvm
  tests/logs/rt.log.WCOSS2_intel
Labels: Ready for Review, Baseline Change, SFSV1, Ready for commit queue

#1299 Add hourly-maximum composite reflectivity and average precip rate fields
  ci/jobs-dev/run_post_mpas_HERCULES.sh
  ci/jobs-dev/run_post_mpas_ORION.sh
  ci/jobs-dev/run_post_mpas_URSA.sh
  ci/jobs-dev/run_post_mpas_WCOSS2.sh
  parm/mpas/postxconfig-NT-rrfs_mpas.txt
  parm/mpas/rrfs_mpas_postcntrl.xml
  parm/params_grib2_tbl_new
  parm/params_grib2_tbl_new.text
  parm/post_avblflds.xml
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/DEALLOCATE.f
  sorc/ncep_post.fd/INITPOST_MPAS.F
  sorc/ncep_post.fd/MDLFLD.f
  sorc/ncep_post.fd/SURFCE.f
  sorc/ncep_post.fd/VRBLS2D_mod.f
  tests/logs/rt.log.HERCULES_intel
  tests/logs/rt.log.ORION_intel
  tests/logs/rt.log.URSA_intel
  tests/logs/rt.log.URSA_intelllvm
  tests/logs/rt.log.WCOSS2_intel
Labels: enhancement, Ready for Review, Baseline Change, MPAS

#1305 Add a check for Ursa to detect_machine.sh
  tests/detect_machine.sh
  tests/logs/rt.log.HERCULES_intel
  tests/logs/rt.log.ORION_intel
  tests/logs/rt.log.URSA_intel
  tests/logs/rt.log.URSA_intelllvm
  tests/logs/rt.log.WCOSS2_intel
Labels: bug, Ready for Review, No Baseline Change, Ready for commit queue

#1311 Update the UPP control files for 3drtma
  ci/spack.yaml
  modulefiles/wcoss2.lua
  modulefiles/wcoss2_a.lua
  parm/params_grib2_tbl_new
  parm/params_grib2_tbl_new.text
  parm/postxconfig-NT-3drtma.txt
Labels: 3DRTMA

#1309 Update UPP Variable Table
  doc/UserGuide/tables/UFS_unified_variables_table.csv
Labels: documentation, Ready for Review
