Repository NOAA-EMC/UPP, pull requests merged in 2025-02, with the labels that each got.

#1129 Merge Gaea modulefiles
  modulefiles/gaea.lua
  modulefiles/gaeac5.lua
  tests/detect_machine.sh
Labels: enhancement, Ready for Review, No Baseline Change, Ready for commit queue

#1132 RRFS–MPAS: Add the U. Utah SLR field ("SDEN")
  parm/postxconfig-NT-rrfs_mpas.txt
  parm/rrfs_mpas_postcntrl.xml
  sorc/ncep_post.fd/DEALLOCATE.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, MPAS, Ready for commit queue

#1146 Clean up GFS post-processing workflow scripts and add back ICEG, ICETMP
  ci/jobs-dev/run_ifi_standalone_fv3r_HERA.sh
  ci/jobs-dev/run_ifi_standalone_hrrr_HERA.sh
  ci/jobs-dev/run_post_fv3r_ifi_HERA.sh
  ci/jobs-dev/run_post_fv3r_ifi_missing_HERA.sh
  ci/jobs-dev/run_post_fv3r_ifi_missing_HERCULES.sh
  ci/jobs-dev/run_post_fv3r_ifi_missing_ORION.sh
  ci/jobs-dev/run_post_hrrr_ifi_HERA.sh
  jobs/JGLOBAL_ATMOS_NCEPPOST
  jobs/JGLOBAL_ATMOS_POST_MANAGER
  jobs/J_NCEPPOST
  parm/gfs/postcntrl_gfs.xml
  parm/gfs/postcntrl_gfs_anl.xml
  parm/gfs/postcntrl_gfs_f00.xml
  parm/gfs/postcntrl_gfs_f00_two.xml
  parm/gfs/postcntrl_gfs_flux.xml
  parm/gfs/postcntrl_gfs_flux_f00.xml
  parm/gfs/postcntrl_gfs_two.xml
  parm/gfs/postxconfig-NT-gfs-anl.txt
  parm/gfs/postxconfig-NT-gfs-f00-two.txt
  parm/gfs/postxconfig-NT-gfs-f00.txt
  parm/gfs/postxconfig-NT-gfs-flux-f00.txt
  parm/gfs/postxconfig-NT-gfs-flux.txt
  parm/gfs/postxconfig-NT-gfs-two.txt
  parm/gfs/postxconfig-NT-gfs.txt
  parm/makefile
  scripts/exgdas_atmos_nceppost.sh
  scripts/exgfs_atmos_nceppost.sh
  scripts/exglobal_atmos_pmgr.sh
  scripts/exwafs_atmos_nceppost.sh
  scripts/run_upp
  sorc/ncep_post.fd/CALVESSEL.f
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
  ush/fix_precip.sh
  ush/fv3gfs_downstream_nems.sh
  ush/fv3gfs_dwn_nems.sh
  ush/gfs_nceppost.sh
  ush/gfs_transfer.sh
  ush/global_nceppost.sh
  ush/link_crtm_fix.sh
  ush/mod_icec.sh
  ush/trim_rh.sh
  ush/wafs_nceppost.sh
Labels: Ready for Review, Baseline Change, GFSV17

#1153 Update gefs control files with adding ICEG and moving aerosol fields
  parm/gefs/postcntrl_gefs.xml
  parm/gefs/postcntrl_gefs_f00.xml
  parm/gefs/postcntrl_gefs_gcafs.xml
  parm/gefs/postxconfig-NT-gefs-f00.txt
  parm/gefs/postxconfig-NT-gefs-gcafs.txt
  parm/gefs/postxconfig-NT-gefs.txt
  parm/makefile
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, GEFSV13, Ready for commit queue
