Repository NOAA-EMC/UPP, pull requests merged in 2025-03, with the labels that each got.

#1154 HAILCAST fix
  sorc/ncep_post.fd/MDL2AGL.f
Labels: Ready for Review, RRFS

#1127 Bug fix for HRRR IFI: Use ifi_apcp if it is 0
  ci/jobs-dev/run_post_hrrr_ifi_HERA.sh
  ci/rt.sh
  sorc/ncep_post.fd/IFI.F
  sorc/ncep_post.fd/SURFCE.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: bug, Ready for Review, Baseline Change, Ready for commit queue

#1150 Add atmospheric products to SFS requested by CPC
  parm/sfs/postcntrl_sfs.xml
  parm/sfs/postxconfig-NT-sfs.txt
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, SFSV1, Ready for commit queue

#1161 Update RRFSv1 UPP control files
  parm/makefile
  parm/rrfs/postxconfig-NT-rrfs.txt
  parm/rrfs/postxconfig-NT-rrfs_f00.txt
  parm/rrfs/postxconfig-NT-rrfs_f01.txt
  parm/rrfs/postxconfig-NT-rrfs_nosmokedust.txt
  parm/rrfs/postxconfig-NT-rrfs_nosmokedust_f00.txt
  parm/rrfs/postxconfig-NT-rrfs_nosmokedust_f01.txt
  parm/rrfs/postxconfig-NT-rrfs_subh.txt
  parm/rrfs/rrfs_postcntrl.xml
  parm/rrfs/rrfs_postcntrl_f00.xml
  parm/rrfs/rrfs_postcntrl_f01.xml
  parm/rrfs/rrfs_postcntrl_nosmokedust.xml
  parm/rrfs/rrfs_postcntrl_nosmokedust_f00.xml
  parm/rrfs/rrfs_postcntrl_nosmokedust_f01.xml
  parm/rrfs/rrfs_postcntrl_subh.xml
Labels: Ready for Review, RRFS

#1159 hafs post floating overflow
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: bug, Ready for Review, No Baseline Change, HAFS, Ready for commit queue

#1168 Add release/rrfs_v1 PRs #1091, #1154, and #1161 to develop branch
  ci/jobs-dev/run_post_3drtma_HERA.sh
  ci/jobs-dev/run_post_3drtma_HERCULES.sh
  ci/jobs-dev/run_post_3drtma_ORION.sh
  ci/jobs-dev/run_post_3drtma_pe_test_HERA.sh
  ci/jobs-dev/run_post_3drtma_pe_test_HERCULES.sh
  ci/jobs-dev/run_post_3drtma_pe_test_ORION.sh
  ci/jobs-dev/run_post_fv3r_HERA.sh
  ci/jobs-dev/run_post_fv3r_HERCULES.sh
  ci/jobs-dev/run_post_fv3r_ORION.sh
  ci/jobs-dev/run_post_fv3r_pe_test_HERA.sh
  ci/jobs-dev/run_post_fv3r_pe_test_HERCULES.sh
  ci/jobs-dev/run_post_fv3r_pe_test_ORION.sh
  parm/makefile
  parm/post_avblflds.xml
  parm/rrfs/postxconfig-NT-rrfs.txt
  parm/rrfs/postxconfig-NT-rrfs_f00.txt
  parm/rrfs/postxconfig-NT-rrfs_f01.txt
  parm/rrfs/postxconfig-NT-rrfs_nosmokedust.txt
  parm/rrfs/postxconfig-NT-rrfs_nosmokedust_f00.txt
  parm/rrfs/postxconfig-NT-rrfs_nosmokedust_f01.txt
  parm/rrfs/postxconfig-NT-rrfs_subh.txt
  parm/rrfs/rrfs_postcntrl.xml
  parm/rrfs/rrfs_postcntrl_f00.xml
  parm/rrfs/rrfs_postcntrl_f01.xml
  parm/rrfs/rrfs_postcntrl_nosmokedust.xml
  parm/rrfs/rrfs_postcntrl_nosmokedust_f00.xml
  parm/rrfs/rrfs_postcntrl_nosmokedust_f01.xml
  parm/rrfs/rrfs_postcntrl_subh.xml
  parm/rrfs_mpas_postcntrl.xml
  sorc/ncep_post.fd/MDL2AGL.f
  sorc/ncep_post.fd/grib2_module.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, Baseline Change, RRFS, Ready for commit queue

#1171 Memcheck fixes
  ci/jobs-dev/run_post_fv3gfs_HERCULES.sh
  ci/jobs-dev/run_post_fv3gfs_ORION.sh
  ci/jobs-dev/run_post_fv3gfs_pe_test_HERCULES.sh
  ci/jobs-dev/run_post_fv3gfs_pe_test_ORION.sh
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/xml_perl_data.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: bug, Ready for Review, GFSV17
