Repository NOAA-EMC/UPP, pull requests merged in 2025-09, with the labels that each got.

#1321 Remove Legacy Satellite Products v2.0
  doc/UserGuide/tables/UPP_GRIB2_Table_byID.csv
  parm/post_avblflds.xml
  sorc/ncep_post.fd/CALRAD_WCLOUD_newcrtm.f
  tests/logs/rt.log.HERCULES_intel
  tests/logs/rt.log.ORION_intel
  tests/logs/rt.log.URSA_intel
  tests/logs/rt.log.URSA_intelllvm
  tests/logs/rt.log.WCOSS2_intel
Labels: documentation, enhancement, Ready for Review, No Baseline Change, Ready for commit queue

#1325 fix surface spfh: read it in when available and set missing if not
  ci/jobs-dev/run_post_rrfs_WCOSS2.sh
  ci/rt.sh
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/SURFCE.f
  tests/logs/rt.log.HERCULES_intel
  tests/logs/rt.log.ORION_intel
  tests/logs/rt.log.URSA_intel
  tests/logs/rt.log.URSA_intelllvm
  tests/logs/rt.log.WCOSS2_intel
Labels: bug, Ready for Review, Baseline Change, RRFS, Ready for commit queue

#1334 Fix surface specific humidity calculation (release/rrfs_v1 branch)
  sorc/ncep_post.fd/INITPOST_NETCDF.f
  sorc/ncep_post.fd/SURFCE.f
Labels: bug, RRFS
