Repository NOAA-EMC/UPP, pull requests merged in 2025-01, with the labels that each got.

#1107 Load cmake on wcoss2 at build time
  modulefiles/wcoss2.lua
Labels: enhancement, Ready for Review, Ready for commit queue

#1072 New Velocity Potential and Stream Function Calculations
  parm/post_avblflds.xml
  parm/sfs/postcntrl_sfs.xml
  parm/sfs/postxconfig-NT-sfs.txt
  sorc/ncep_post.fd/MDL2P.f
  sorc/ncep_post.fd/UPP_PHYSICS.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review, SFSV1, Ready for commit queue

#1112 RRFS-MPAS: read-in and output graupel number concentration
  parm/post_avblflds.xml
  parm/postxconfig-NT-rrfs_mpas.txt
  parm/rrfs_mpas_postcntrl.xml
  sorc/ncep_post.fd/ALLOCATE_ALL.f
  sorc/ncep_post.fd/DEALLOCATE.f
  sorc/ncep_post.fd/INITPOST_MPAS.F
  sorc/ncep_post.fd/MDL2P.f
  sorc/ncep_post.fd/MDLFLD.f
  sorc/ncep_post.fd/VRBLS3D_mod.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, No Baseline Change, MPAS, Ready for commit queue

#1115 Rename shortname for ID 1021 and 1022
  parm/post_avblflds.xml
  parm/sfs/postcntrl_sfs.xml
  parm/sfs/postxconfig-NT-sfs.txt
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: bug, Ready for Review, No Baseline Change, SFSV1, Ready for commit queue

#1116 Updating Gaea C6 modulefile for UPP.
  modulefiles/gaeac6.lua
Labels: bug, Ready for Review, No Baseline Change, Ready for commit queue
