Repository NOAA-EMC/UPP, pull requests merged in 2025-06, with the labels that each got.

#1220 Remove hardcoded bucket value for ensemble products
  sorc/ncep_post.fd/xml_perl_data.f
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: enhancement, Ready for Review, GEFSV13, Ready for commit queue

#1221 Add 50m winds to SFS products list
  parm/sfs/postcntrl_sfs.xml
  parm/sfs/postxconfig-NT-sfs.txt
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
Labels: Ready for Review, SFSV1, Ready for commit queue

#1231 Port UPP to Ursa (build only; no regtest)
  modulefiles/gaea_intel.lua
  modulefiles/hera_intel.lua
  modulefiles/hera_intel_external_ifi.lua
  modulefiles/hera_intel_ifi_test_prereqs.lua
  modulefiles/hercules_intel.lua
  modulefiles/jet_intel.lua
  modulefiles/jet_intel_external_ifi.lua
  modulefiles/jet_intel_ifi_test_prereqs.lua
  modulefiles/noaacloud_intel.lua
  modulefiles/orion_intel.lua
  modulefiles/s4_intel.lua
  modulefiles/ursa_intel.lua
  modulefiles/ursa_intelllvm.lua
  modulefiles/wcoss2_a_intel.lua
  modulefiles/wcoss2_intel.lua
  tests/compile_upp.sh
  tests/detect_machine.sh
  tests/logs/rt.log.HERA
  tests/logs/rt.log.HERCULES
  tests/logs/rt.log.ORION
  tests/logs/rt.log.WCOSS2
Labels: enhancement, Ready for Review, Ready for commit queue

#1240 UUtah SLR algorithm bug fix RH converted from decimal to percent
  sorc/ncep_post.fd/UPP_PHYSICS.f
  tests/logs/rt.log.HERA_intel
  tests/logs/rt.log.HERCULES_intel
  tests/logs/rt.log.ORION_intel
  tests/logs/rt.log.URSA_intel
  tests/logs/rt.log.URSA_intelllvm
  tests/logs/rt.log.WCOSS2_intel
Labels: Ready for Review, Baseline Change, GFSV17, MPAS

#1246 NINT(Zm10c) in MDLFLD.f for integer array index
  sorc/ncep_post.fd/MDLFLD.f
  tests/logs/rt.log.HERA_intel
  tests/logs/rt.log.HERCULES_intel
  tests/logs/rt.log.HERCULES_intelllvm
  tests/logs/rt.log.ORION_intel
  tests/logs/rt.log.ORION_intelllvm
  tests/logs/rt.log.URSA_intel
  tests/logs/rt.log.URSA_intelllvm
  tests/logs/rt.log.WCOSS2_intel
Labels: bug, Ready for Review, No Baseline Change, Ready for commit queue
